### PR TITLE
Light color scheme

### PR DESCRIPTION
**Pull request by Sevastiyan**
Updated the colors into the light color scheme using the colors for the Horizon light theme.

### CODE REVIEW

**Comment by xShivan** [comment]
Cool, I'm going to check how it looks as soon as I can before merging.

Does it support new Jetbrains UI themes?

**Comment by Sevastiyan** [comment]
Yes it seems that most of it is acting as normal.

**Comment by Sevastiyan** [comment]
* I have tested it on IntelliJ 2019.3

**Comment by xShivan** [comment]
Looks good! I'm merging it. I'm going to add screenshot to README.md later.

**Pull request merged**
